
format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\

$git_branch\
$git_state\
$git_metrics\
$git_status\

$nix_shell\
$direnv\
$env_var\
$custom\
$cmd_duration\

$line_break\
$jobs\
$battery\
$container\
$character"""

add_newline = false

[character]
success_symbol = '[⮞](bold green)'
error_symbol = '[⮞](bold red)'
vicmd_symbol = '[⮜](bold green)'

[username]
format = '[$user]($style)@'
show_always = true

[hostname]
ssh_only = false
format = '[$hostname]($style) in '

[git_metrics]
disabled = false

[[battery.display]]
threshold = 20

