#!/bin/sh

export TERMINAL=wezterm

nitrogen --restore &

picom &

# System tray
nm-applet --no-agent &
volumeicon &
blueberry-tray &

# pressing super alone simulates Alt-F1
ksuperkey -e 'Super_L=Alt_L|F1' &

# swap caps lock and escape
setxkbmap -option caps:swapescape
